# Generated by Django 2.0.2 on 2018-03-01 18:42

from django.db import migrations, models
import example_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        example_app.models.Point.Operation(),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', example_app.models.PointField()),
            ],
        ),
    ]
